import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'index',
    {
      type: 'category',
      label: 'Themen',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'themen'}],
    },
    {
      type: 'category',
      label: 'Konzepte',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'konzepte'}],
    },
    {
      type: 'category',
      label: 'Publikationen',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'publikationen'}],
    },
  ],
};

export default sidebars;
